# Generated by Django 5.2.6 on 2025-10-01 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_chat_group_name_chat_group_photo_chat_is_group_chat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_quote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='quote_text',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='post',
            name='repost_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reposts', to='core.post'),
        ),
    ]
